export const cardsData = [
  {
    id: 1,
    topic: "Web Design",
    title: "Название задачи 1",
    date: "30.10.23",
    status: "Без статуса",
    theme: "_orange",
    description: "Описание задачи 1",
  },
  {
    id: 2,
    topic: "Research",
    title: "Название задачи 2",
    date: "31.10.23",
    status: "Нужно сделать",
    theme: "_green",
    description: "Описание задачи 2",
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Название задачи 3",
    date: "01.11.23",
    status: "В работе",
    theme: "_purple",
    description: "Описание задачи 3",
  },
  {
    id: 4,
    topic: "Web Design",
    title: "Название задачи 4",
    date: "02.11.23",
    status: "Тестирование",
    theme: "_orange",
    description: "Описание задачи 4",
  },
  {
    id: 5,
    topic: "Research",
    title: "Название задачи 5",
    date: "03.11.23",
    status: "Готово",
    theme: "_green",
    description: "Описание задачи 5",
  },
  {
    id: 6,
    topic: "Web Design",
    title: "Название задачи 6",
    date: "04.11.23",
    status: "Без статуса",
    theme: "_orange",
    description: "Описание задачи 6",
  },
  {
    id: 7,
    topic: "Copywriting",
    title: "Название задачи 7",
    date: "05.11.23",
    status: "Нужно сделать",
    theme: "_purple",
    description: "Описание задачи 7",
  },
];
